"use server"

import { JSDOM } from "jsdom"
import { Readability } from "@mozilla/readability"

export async function generateLlmsText(url: string): Promise<{ text?: string; error?: string }> {
  try {
    // Validate URL
    let targetUrl: URL
    try {
      targetUrl = new URL(url)
    } catch (e) {
      return { error: "Invalid URL. Please enter a valid URL including the protocol (http:// or https://)." }
    }

    // Fetch the webpage content
    const response = await fetch(targetUrl.toString(), {
      headers: {
        "User-Agent": "GEO Generator Bot/1.0",
      },
    })

    if (!response.ok) {
      return { error: `Failed to fetch the website: ${response.status} ${response.statusText}` }
    }

    const html = await response.text()

    // Parse the HTML
    const dom = new JSDOM(html, { url: targetUrl.toString() })
    const document = dom.window.document

    // Extract the title
    const title = document.title || "Untitled Document"

    // Use Readability to extract the main content
    const reader = new Readability(document)
    const article = reader.parse()

    if (!article || !article.content) {
      return { error: "Could not extract meaningful content from the provided URL." }
    }

    // Create a temporary DOM to clean up the HTML
    const tempDom = new JSDOM(article.content)
    const tempDoc = tempDom.window.document

    // Remove scripts, styles, and other non-content elements
    const elementsToRemove = tempDoc.querySelectorAll("script, style, iframe, noscript, svg")
    elementsToRemove.forEach((el) => el.remove())

    // Format according to llmstxt.org specifications
    let llmsText = `# ${title}\n\n`

    // Add URL as source
    llmsText += `Source: ${targetUrl.toString()}\n\n`

    // Add content
    // Convert HTML to plain text, preserving paragraph structure
    const paragraphs = Array.from(tempDoc.body.querySelectorAll("p, h1, h2, h3, h4, h5, h6, ul, ol, blockquote"))

    paragraphs.forEach((p) => {
      if (p.tagName.toLowerCase().startsWith("h")) {
        // Handle headings
        const level = Number.parseInt(p.tagName.substring(1))
        const prefix = "#".repeat(level)
        llmsText += `${prefix} ${p.textContent?.trim()}\n\n`
      } else if (p.tagName.toLowerCase() === "ul" || p.tagName.toLowerCase() === "ol") {
        // Handle lists
        const items = Array.from(p.querySelectorAll("li"))
        items.forEach((item) => {
          llmsText += `- ${item.textContent?.trim()}\n`
        })
        llmsText += "\n"
      } else if (p.tagName.toLowerCase() === "blockquote") {
        // Handle blockquotes
        llmsText += `> ${p.textContent?.trim()}\n\n`
      } else {
        // Handle regular paragraphs
        llmsText += `${p.textContent?.trim()}\n\n`
      }
    })

    // Add metadata
    llmsText += `---\nGenerated by GEO Generator on ${new Date().toISOString()}\n`

    return { text: llmsText }
  } catch (error) {
    console.error("Error generating llms.txt:", error)
    return { error: "An error occurred while processing the website content." }
  }
}
